POST https://itc-bootcamp-19-dot-charcha-dev.appspot.com/tweet
content-type: application/json

{
    "tweet": {
        "userName": "John",
        "content": "Yo!",
        "date": "2020-05-08T10:21:35.486Z"
    }
}